// src/components/Nav.jsx
import React from "react";
import TotalBlance  from "./TotalBlance";

function Nav() {
    return (
        <div className="nav">
            <blockquote className="flex around">
                <h3 className="mrgin5px fff">
                    Google Wallet
                </h3>

                <div className="blanceBox">
                    <i className="fa-solid fa-bangladeshi-taka-sign"></i>
                    <span>
                        <TotalBlance/>
                    </span>
                    TK
                </div>
            </blockquote>
        </div>
    );
}


export default Nav;

// src/components/Nav.vue
<template>
  <div class="nav flex around">

    <div>
      <h3 class="mrgin5px fff">
        {{ logo }}
      </h3>
    </div>
    <div>
      <div class="blanceBox">
        <i class="fa-solid fa-bangladeshi-taka-sign"></i> 
        <span id="taka">
          500.00
          <i class="fa-solid fa-arrow-rotate-right fa-spin"></i>
        </span>
        TK
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Nav',
  data(){
    return{
      logo:'Google Wallet'
    }
  }
}
</script>
